spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/gold
  application:
    name: mongoweb
  http:
      multipart:
        max-file-size: 100Mb
        maxRequestSize: 100Mb
server:
  port: 8888


structUrl: http://47.97.42.87:8081

