spring:
  data:
    mongodb:
      primary:
        database: gold
        host: 127.0.0.1
        password:
        username:
        port: 27017
#      uri: mongodb://localhost:27017/gold
      secondary:
        database: wangxi-test
        host: 121.196.244.147
        password: wx123456
        username: wx
        port: 3717

  application:
    name: mongoweb
  http:
      multipart:
        max-file-size: 100Mb
        maxRequestSize: 100Mb
server:
  port: 8888


structUrl: http://47.97.42.87:8081

